version: '3'
services:
  haproxy:
    image: labhaproxy2
    build:
      context: .
      dockerfile: haproxy.dockerfile
    expose:
      - 80
    ports:
      - "8081:80"
    depends_on:
      - gunicorn
  gunicorn:
    image: labgunicorn
    build:
      context: .
      dockerfile: gunicorn.dockerfile
    ports:
        - "8082:6767"
